extends Node2D

var ENEMY_MAX_HEALTH=20
var ENEMY_SWORD_DAMAGE=4
var ENEMY_MAGIC_DAMAGE=7
var SKELETON_POSITION=Vector2.ZERO

var BOSS_ENEMY_FIRE_DAMAGE=8

var PLAYER_POSITION_X=0
var PLAYER_POSITION=0
var PLAYER_MAX_HEALTH=100
var PLAYER_SWORD_DAMAGE=5
var PLAYER_MAGIC_DAMAGE=10
var POTIONS_REVIVAL=10
var REMOVE_PLAYER_UI=false

var NUM_KEYS=0
var SCORE=0
var COINS=0
var TREASURE_NO=0
var COMPLETE=false

var CHECKPOINT_LOCATION=0
var IS_PLAYER_FLIPPED=false
var LEVEL_COMPLETE=false
var LEVEL_FAILED=false
var CAN_SPAWN_SKELETON=false

var save={}

func _ready() -> void:
	pass
